### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by Karla02** [jelordreygulle/IC-Enrollment-System#1]
Where is the .sql file?

**Comment by jelordreygulle** [comment]
Why is that you are interested on the sql file?

**Comment by jelordreygulle** [comment]
tell me the purpose and i could provide you the file

**Comment by gallardov** [comment]
Sir can I get you SQL, purpose for the SAD suject  ør System Analysis And Design subject.....

**Comment by jelordreygulle** [comment]
I'll be sending you an update when I find the sql file , I think I have stored in somewhere.
